### ISSUE TITLE
on click event

### ISSUE THREAD

**Issue by ssjogus** [smachs/jquery-fab-button#1]
hi,

thank you very much for separating FAB and providing as separate plugin. The FAB is opening on mouseover. How to do in on click? Any advice?

any help will be appreciated..

**Comment by sterlingdiazd** [comment]
First, I'm not the creator of the plugin. What you are looking at, I will that myself for a project I'm working with when I it's time. The answer is pretty simple. To the FAB button, you change the event onMouseOver for onClick with js, and that's it! In the callback you show the menu items.

**Comment by smachs** [comment]
> hi,
> 
> thank you very much for separating FAB and providing as separate plugin. The FAB is opening on mouseover. How to do in on click? Any advice?
> 
> any help will be appreciated..

> First, I'm not the creator of the plugin. What you are looking at, I will that myself for a project I'm working with when I it's time. The answer is pretty simple. To the FAB button, you change the event onMouseOver for onClick with js, and that's it! In the callback you show the menu items.

Exactly as @sterlingdiazd said use change the event **onMouseOver** for **onClick** with js. I'm preparing an API for the FAB to wait a few days :blush:

**Comment by ivnnv** [comment]
You can just add `click-to-toggle` class to the parent div [as stated on the original materializecss component API doc](https://materializecss.com/floating-action-button.html#click-only)
